### ISSUE TITLE
Setting a package to { url: "gitrepo", ref: "branch" } throws an error.

### ISSUE THREAD

**Issue by mrozbarry** [gdotdesign/elm-github-install#15]
In advanced usage, you have an example of:

```
"gdotdesign/elm-install-test": {
  "url": "gdotdesign@bitbucket.org:gdotdesign/elm-install-test",
  "ref": "master"
}
```

But doing that in my code throws:

```
/Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/utils.rb:20:in `transform_constraint': undefined method `gsub!' for #<Hash:0x007fdb441d0598> (NoMethodError)
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/resolver.rb:43:in `block in add_dependencies'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/resolver.rb:40:in `each'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/resolver.rb:40:in `flat_map'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/resolver.rb:40:in `add_dependencies'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/resolver.rb:26:in `add_constraints'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/installer.rb:73:in `retry_install'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/installer.rb:52:in `rescue in install'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install/installer.rb:46:in `install'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/lib/elm_install.rb:24:in `install'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/elm_install-0.3.1/bin/elm-install:18:in `block (2 levels) in <top (required)>'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from /Users/mrozbarry/.elm-install/elm-install-0.3.1-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

It looks like your spec tests only test if a repository string, and not if it's a hash with url and ref.

**Comment by gdotdesign** [comment]
For me with 0.3.1 for this `elm-package.json`:
```
{
  "dependencies": {
    "elm-lang/svg": "2.0.0 <= v < 3.0.0",
    "elm-lang/dom": "1.1.1 <= v < 2.0.0",
    "elm-lang/core": "5.0.0 <= v < 6.0.0",
    "gdotdesign/elm-install-test": "1.0.0 <= v < 2.0.0"
  },
  "dependency-sources": {
    "gdotdesign/elm-install-test": {
      "url": "gdotdesign@bitbucket.org:gdotdesign/elm-install-test",
      "ref": "master"
    }
  }
}
```
works correctly:
```
$ elm-install --cache-directory ./cache
Resolving packages...
  ▶ Package: https://github.com/elm-lang/svg not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/core not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/html not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/virtual-dom not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/dom not found in cache, cloning...
  ▶ Package: gdotdesign@bitbucket.org:gdotdesign/elm-install-test not found in cache, cloning...
Solving dependencies...
Saving package cache...
  ● elm-lang/svg - 2.0.0 (2.0.0)
  ● elm-lang/dom - 1.1.1 (1.1.1)
  ● elm-lang/core - 5.1.1 (5.1.1)
  ● gdotdesign/elm-install-test - 1.0.0 (master)
  ● elm-lang/html - 2.0.0 (2.0.0)
  ● elm-lang/virtual-dom - 2.0.4 (2.0.4)
Packages configured successfully!
```

Maybe you added it to the `dependencies` field instead of the `dependency-sources`?

**Comment by mrozbarry** [comment]
You are correct, I just misread the docs. Thanks for clearing that up.
