### ISSUE TITLE
Symlinks on Windows

### ISSUE THREAD

**Issue by jirisliva** [gdotdesign/elm-github-install#36]
When we define dependency-source as local folder then elm-install want to create symlink pointing to that folder. This works on macOS or Linux but on Windows we got error reported by FileUtils.rb

```
symlink': symlink() function is unimplemented on this machine (NotImplementedError)
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/ruby/lib/ruby/2.2.0/fileutils.rb:357:in `block in ln_s'
```
This issue (creating symbolic link on Windows) seems to be solved in Ruby 2.3. Do you have plan to update to 2.3?

Entire report:
```
C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/ruby/lib/ruby/2.2.0/fileutils.rb:357:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/ruby/lib/ruby/2.2.0/fileutils.rb:357:in `block in ln_s'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/ruby/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/ruby/lib/ruby/2.2.0/fileutils.rb:355:in `ln_s'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install/directory_source.rb:43:in `copy_to'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install/populator.rb:59:in `block in copy_dependencies'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install/populator.rb:52:in `each'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install/populator.rb:52:in `copy_dependencies'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install/populator.rb:21:in `populate'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install/installer.rb:26:in `install'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/lib/elm_install.rb:41:in `install'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.1.0/bin/elm-install:18:in `block (2 levels) in <top (required)>'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:71:in `run!'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from C:/Users/aprialuk/.elm-install/elm-install-1.1.0-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by gdotdesign** [comment]
Travelling Ruby is used to distribute the application on NPM and the latest it supports is 2.2.

I think the [gem](https://rubygems.org/gems/elm_install) should work if installed on 2.3 (with `gem install elm_install`), can you test if it works this way?

**Comment by jirisliva** [comment]
With elm-install installed as Ruby gem it works perfectly. Thanks.

**Comment by gdotdesign** [comment]
Thanks for testing and pointing it out :+1:  I'll add a note about this to the Readme, until then I'll leave this issue open.

**Comment by gdotdesign** [comment]
Added a note to the readme about this, closing.
