### ISSUE TITLE
Error installing mgold/elm-date-format

### ISSUE THREAD

**Issue by hpate-omicron** [gdotdesign/elm-github-install#37]
First, thank you for the library, it has made it way easier to handle private Elm packages!

I noticed this on our CI when it updated to v1.3.0, it didn't happen previously on v1.2.0:

Short version:
```
elm-github-install install
Resolving packages...
  ▶ Getting updates for: mgold/elm-date-format
error: git '--git-dir=/Users/hpate/.elm-install/github.com/mgold/elm-date-format/.git' '--work-tree=/Users/hpate/.elm-install/github.com/mgold/elm-date-format' checkout '0.1.0'  2>&1:error: pathspec '0.1.0' did not match any file(s) known to git.. Use --trace to view backtrace
```

With `trace` on:
```
$ elm-github-install --trace
Resolving packages...
  ▶ Getting updates for: mgold/elm-date-format
/Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/Users/hpate/.elm-install/github.com/mgold/elm-date-format/.git' '--work-tree=/Users/hpate/.elm-install/github.com/mgold/elm-date-format' checkout '0.1.0'  2>&1:error: pathspec '0.1.0' did not match any file(s) known to git. (Git::GitExecuteError)
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/git-1.3.0/lib/git/lib.rb:644:in `checkout'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/git-1.3.0/lib/git/base.rb:306:in `checkout'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/repository.rb:36:in `checkout'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/git_source.rb:44:in `fetch'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/git_source.rb:104:in `block in matching_versions'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/git_source.rb:103:in `select'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/git_source.rb:103:in `matching_versions'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/git_source.rb:89:in `versions'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/resolver.rb:43:in `resolve_dependency'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/resolver.rb:26:in `block in resolve'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/resolver.rb:25:in `each'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/resolver.rb:25:in `resolve'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install/installer.rb:23:in `install'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/lib/elm_install.rb:40:in `install'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/elm_install-1.3.0/bin/elm-install:18:in `block (2 levels) in <top (required)>'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/hpate/.nvm/versions/node/v8.2.1/lib/node_modules/elm-github-install/scripts/dist-1.3.0/elm-install-1.3.0-osx/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```
Minimal case:
```
{
    "version": "1.0.0",
    "dependencies": {
        "mgold/elm-date-format": "1.4.0 <= v < 2.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

I looked through the `elm-date-format` repo and I think it may be that the `0.1.0` version is tagged as `0.1` in the Github release - https://github.com/mgold/elm-date-format/releases?after=0.1.1

Here's the output from v1.2.0:
```
elm-github-install install
Resolving packages...
  ▶ Getting updates for: mgold/elm-date-format
  ▶ Getting updates for: elm-lang/core
Solving dependencies...
  ● mgold/elm-date-format - https://github.com/mgold/elm-date-format (1.4.0)
  ● elm-lang/core - https://github.com/elm-lang/core (5.1.1)
Packages configured successfully!
```

**Comment by gdotdesign** [comment]
> First, thank you for the library, it has made it way easier to handle private Elm packages!

Glad to hear it! :tada: 

Nice catch and I really appreciate the minimal case :+1: :smile: 

Fixed in 1.4.0 - https://github.com/gdotdesign/elm-github-install/releases/tag/v1.4.0
