### ISSUE TITLE
Can't install with local path in "dependency-sources"

### ISSUE THREAD

**Issue by mrmurphy** [gdotdesign/elm-github-install#49]
I've added a local path to "dependency-sources" (I've tried both relative and absolute paths). My `elm-package.json` looks like this:

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "",
    "source-directories": [
        "./src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "mdgriffith/style-elements": "4.1.0 <= v < 5.0.0",
        "bloom/bb": "1.0.0 <= v < 2.0.0"
    },
    "dependency-sources": {
      "bloom/bb": "../bloom/bb",
    }, 
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

I've deleted `elm-stuff`, and whenever I run `elm-install` I get the following error message:

```
λ elm-install --trace
Resolving packages...
Solving dependencies...
/Library/Ruby/Gems/2.3.0/gems/elm_install-1.6.1/lib/elm_install/populator.rb:30:in `binwrite': No such file or directory @ rb_sysopen - elm-stuff/exact-dependencies.json (Errno::ENOENT)
        from /Library/Ruby/Gems/2.3.0/gems/elm_install-1.6.1/lib/elm_install/populator.rb:30:in `write_exact_dependencies'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Library/Ruby/Gems/2.3.0/gems/elm_install-1.6.1/lib/elm_install/populator.rb:22:in `populate'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Library/Ruby/Gems/2.3.0/gems/elm_install-1.6.1/lib/elm_install/installer.rb:28:in `install'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /Library/Ruby/Gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Library/Ruby/Gems/2.3.0/gems/elm_install-1.6.1/lib/elm_install.rb:40:in `install'
        from /Library/Ruby/Gems/2.3.0/gems/elm_install-1.6.1/bin/elm-install:20:in `block (2 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.3.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

I've tried both an `npm` installed version of elm-install, and the globally installed gem.

I've tried creating the `elm-stuff` directory by hand and running `elm-install`, in which case it just writes out an `exact_dependencies.json` file with only an empty object inside, and reports having completed installation successfully.

Running on Mac OS High Sierra 10.13.1 Beta (17B25c) with system ruby (2.3.3p222)

Any ideas?
If I remove the local package from `dependency-sources`, installation of the other packages appears to work as expected.

Thanks for this tool, and for your time!

**Comment by mrmurphy** [comment]
@zwilias pointed out that I've got a trailing comma on that single line in my dependency sources. I removed that, and the install seemed to work just fine!

He tested on his computer with version `1.0.1`, and that version warned him about invalid json in `elm-package.json`. But it appears that `1.6.1` no longer shows that warning.

Again, thanks for the tool! I'll close this issue.

**Comment by gdotdesign** [comment]
> He tested on his computer with version 1.0.1, and that version warned him about invalid json in elm-package.json. But it appears that 1.6.1 no longer shows that warning.

Thanks for reporting this, I think a warning should be there I'll open an issue for this.
