### ISSUE TITLE
Unknown filetype

### ISSUE THREAD

**Issue by martinos** [gdotdesign/elm-github-install#53]
I am on MacOs Sierra  and when I run the command I get the following error message:

```
error: unknown file type: /Users/me/.elm-install/github.com/elm-lang/html/./.git/tags.34360.
```

Here is the call stack
```
/Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1390:in `copy': unknown file type: /Users/me/.elm-install/github.com/elm-lang/keyboard/./.git/tags.35321 (RuntimeError)
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1500:in `call'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1500:in `wrap_traverse'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1503:in `block in wrap_traverse'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1502:in `each'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1502:in `wrap_traverse'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1503:in `block in wrap_traverse'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1502:in `each'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1502:in `wrap_traverse'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:441:in `block in cp_r'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
	from /Users/me/.rubies/ruby-2.1.3/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install/git_source.rb:63:in `copy_to'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install/populator.rb:59:in `block in copy_dependencies'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install/populator.rb:52:in `each'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install/populator.rb:52:in `copy_dependencies'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install/populator.rb:21:in `populate'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install/installer.rb:28:in `install'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
	from /Users/me/.gem/ruby/2.1.3/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/lib/elm_install.rb:40:in `install'
	from /Users/me/.gem/ruby/2.1.3/gems/elm_install-1.6.1/bin/elm-install:20:in `block (2 levels) in <top (required)>'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.gem/ruby/2.1.3/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'

```

I get the same error when using the npm version. 

It seems that this error is not bound to a specific package.

**Comment by martinos** [comment]
It seems that the file that the gem is trying to copy does not exist anymore. Is there some kind of threading in the library?

**Comment by DerekMaffett** [comment]
I just had this same problem - how does your dependency sources look? I was having this when I used the string reference to the repo, but it seems to have gone away when I used the object format 

```
        "publisher/package": {
            "url": "git@bitbucket.org:publisher/package.git",
            "ref": "master"
        }
```

I'm guessing something about the tags. For me, the error always occurred for a separate dependency but was actually triggered by the repo dependency. 

Edit: Nevermind, it broke again. Honestly, it seems almost random.
