### ISSUE TITLE
elm-install fails with error: "\xC2" on US-ASCII.

### ISSUE THREAD

**Issue by shamis** [gdotdesign/elm-github-install#55]
following is the stacktrace obtained when executing `elm-install --trace`
```
/usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `encode': "\xC2" on US-ASCII (Encoding::InvalidByteSequenceError)
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `initialize'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `new'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/ruby/lib/ruby/2.2.0/json/common.rb:155:in `parse'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/identifier.rb:134:in `json'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/identifier.rb:35:in `dependency_sources'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/identifier.rb:22:in `initialize'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/installer.rb:14:in `new'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/installer.rb:14:in `initialize'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install.rb:40:in `new'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install.rb:40:in `install'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/bin/elm-install:20:in `block (2 levels) in <top (required)>'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/share/.config/yarn/global/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-linux-x86_64/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by shamis** [comment]
Sorry, false alarm
Issue was solved by setting the locale to utf-8
