### ISSUE TITLE
error: No such file or directory @ rb_sysopen - elm-stuff/exact-dependencies.json.

### ISSUE THREAD

**Issue by polyrtm** [gdotdesign/elm-github-install#65]
Whenever I try to run elm-install, I get that error. The gem installs fine.
Trace: ```
Resolving packages...
Solving dependencies...
Traceback (most recent call last):
        20: from /home/jackfly26/.gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
        19: from /home/jackfly26/.gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        18: from /home/jackfly26/.gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
        17: from /home/jackfly26/.gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        16: from /home/jackfly26/.gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        15: from /home/jackfly26/.gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        14: from /home/jackfly26/.gem/ruby/2.6.0/gems/elm_install-1.6.1/bin/elm-install:20:in `block (2 levels) in <top (required)>'
        13: from /home/jackfly26/.gem/ruby/2.6.0/gems/elm_install-1.6.1/lib/elm_install.rb:40:in `install'
        12: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        11: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        10: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
         9: from /home/jackfly26/.gem/ruby/2.6.0/gems/elm_install-1.6.1/lib/elm_install/installer.rb:28:in `install'
         8: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
         7: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
         6: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
         5: from /home/jackfly26/.gem/ruby/2.6.0/gems/elm_install-1.6.1/lib/elm_install/populator.rb:22:in `populate'
         4: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
         3: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
         2: from /home/jackfly26/.gem/ruby/2.6.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
         1: from /home/jackfly26/.gem/ruby/2.6.0/gems/elm_install-1.6.1/lib/elm_install/populator.rb:30:in `write_exact_dependencies'
/home/jackfly26/.gem/ruby/2.6.0/gems/elm_install-1.6.1/lib/elm_install/populator.rb:30:in `binwrite': No such file or directory @ rb_sysopen - elm-stuff/exact-dependencies.json (Errno::ENOENT)```

**Comment by SidneyNemzer** [comment]
I see the last line says:

`No such file or directory @ rb_sysopen - elm-stuff/exact-dependencies.json `

Maybe try running the elm compiler first to generate the `exact-dependencies.json` file.

(Side note: try using triple backticks instead of single backticks here -- that will preserve newlines and make it much easier to read this stacktrace!)
