### ISSUE TITLE
Failed to resolve versions using on Windows

### ISSUE THREAD

**Issue by villasv** [gdotdesign/elm-github-install#8]
Running `elm-github-install` in my Elm project with only `core` and `html` as dependencies, I get this:

```
error { '0':
   Error: Unable to satisfy version constraint: elm-lang/core@>=5.0.0 <6.0.0 from root
       at C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules\semver-resolver\lib\index.js:18
2:25
       at C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules\lodash\lodash.js:4944:15
       at baseForOwn (C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules\lodash\lodash.js:30
01:24)
       at Function.forOwn (C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules\lodash\lodash.
js:13002:24)
       at SemverResolver.maxSatisfying (C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules\s
emver-resolver\lib\index.js:164:24)
       at C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules\semver-resolver\lib\index.js:27
9:32
       at Array.forEach (native)
       at SemverResolver.resolveVersions (C:\Users\villasv\AppData\Roaming\npm\node_modules\elm-github-install\node_modules
\semver-resolver\lib\index.js:274:26)
       at process._tickCallback (internal/process/next_tick.js:103:7) }
```

**Comment by gdotdesign** [comment]
I've released a new version which is a rewrite, can you try it with that?

**Comment by villasv** [comment]
Yep, seems to be working now. Tested with the `elm-architecture-tutorial` plus `simonh1000/file-reader`.

**Comment by gdotdesign** [comment]
Great :+1: thanks, then I'll close this issue now.
